name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List directory contents for debugging
      - name: List directory contents
        run: ls -la

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Verify Cypress installation
      - name: Verify Cypress installation
        run: npx cypress verify

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          # Remove the wait-on and start options since we're testing an external site
          browser: chrome