name: Cypress Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: List directory contents for debugging
      - name: List directory contents
        run: ls -la
      
      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
      
      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install -g newman
      
      # Step 5: Verify Cypress installation
      - name: Verify Cypress installation
        run: npx cypress verify
      
      # Step 6: Run Postman Newman tests
      - name: Run Postman Newman Tests
        run: |
          newman run "cypress/integration/postman_tests/AutomationExercise.postman_collection.json" \
          -e "cypress/integration/postman_tests/AutomationExercise_env.postman_environment.json" \
          --reporters cli,junit \
          --reporter-junit-export "newman-results.xml"
      
      # Step 7: Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      
      # Optional: Upload Newman test results as artifact
      - name: Upload Newman Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: newman-results.xml
          retention-days: 5
